insert into department (department_name)
values ('Software Engineering'),
		('Digital Media'),
		('Cybersecurity'),
		('IT Support'),
		('Information Systems');

insert into instructor (first_name, last_name, email)
values ('John', 'Doe', 'john.doe@cactus-college.edu'),
       ('Jane', 'Smith', 'jane.smith@cactus-college.edu'),
       ('Emma', 'Johnson', 'emma.johnson@cactus-college.edu'),
       ('Olivia', 'Brown', 'olivia.brown@cactus-college.edu'),
       ('Noah', 'Taylor', 'noah.taylor@cactus-college.edu'),
       ('Ava', 'Anderson', 'ava.anderson@cactus-college.edu'),
       ('Liam', 'Wilson', 'liam.wilson@cactus-college.edu'),
       ('Isabella', 'Clark', 'isabella.clark@cactus-college.edu'),
       ('Ethan', 'Thomas', 'ethan.thomas@cactus-college.edu'),
       ('Sophia', 'Harrison', 'sophia.harrison@cactus-college.edu'),
       ('Mason', 'Martin', 'mason.martin@cactus-college.edu'),
       ('Amelia', 'Jackson', 'amelia.jackson@cactus-college.edu'),
       ('Benjamin', 'Forest', 'benjamin.forest@cactus-college.edu'),
       ('Harper', 'Lewis', 'harper.lewis@cactus-college.edu'),
       ('James', 'Jackson', 'james.jackson@cactus-college.edu'),
       ('Mia', 'Milakos', 'mia.milakos@cactus-college.edu'),
       ('Charolette', 'Allen', 'charolette.allen@cactus-college.edu'),
       ('Emily', 'Wright', 'emily.wright@cactus-college.edu'),
       ('Marcy', 'Sears', 'marcy.sears@cactus-college.edu');


insert into course (course_name, course_desc, credits) 
values ('CIS: 101A: Technician IT Fundamentals', 'Survey of computer fundamentals. Focus on basic knowledge and skills, including components and hardware, word processing, presentations, spreadsheets, and email',3),
 ('CIS 101AB: Customer User Support', 'Examines skills, tools and strategies necessary for becoming a computer help-desk or end-user support professional.',3 ),
 ('CIS 111: Introduction to Social Media', 'Identify and explain social media and Web 2.0 technologies for personal, academic, professional, and business applications.',3),
 ('CIS 113: Survey of Computer Information Systems', 'Overview of computer technology, concepts, terminology, and the role of computers in business and society.',3),
 ('CIS 114E: Excel Spreadsheet', 'Computer spreadsheet skills for solving business problems using Excel, including calculations, forecasting, projections, macro programming, database searching, extraction, linking, statistics, and matrix manipulation.',3),
 ('CIS 114MSA: Microsoft Access: Database Management', 'ntroduction to Microsoft Access. Emphasis on features, design, and database management.',3),
 ('CIS114MSP: Desktop Presentation: PowerPoint', 'Use of PowerPoint to produce professional-quality presentation visuals with animation and sound.',3),
 ('CIS 116AI: Introduction to Adobe Illustrator', 'Provides students with the knowledge and skills to use Adobe Illustrator graphics software on a computer.',3),
 ('CIS 116AA: Introduction to Adobe Animate', 'Focuses on entry-level skill expectations for digital animation using Adobe Animate.',3),
 ('CIS 116AP: Introduction to Adobe Photoshop', 'Focuses on entry-level skills and knowledge for digital imaging using Adobe Photoshop.',3),
 ('CIS 116AV: Introduction to Digital Video Editing', 'Introduction to digital video editing comprises of a foundation for video import, export, and editing functions.',3),
 ('CIS 116AAE: Introduction to Adobe After Effects', 'Includes creating visual effects for video projects.',3),
 ('CIS 116AAA: Introduction to Adobe Audition', 'Introduction to editing audio files in a multitrack editing environment using Adobe Audition.',3),
 ('CIS 117: Windows Operating System: Level I', 'Specific topics include Windows basics.',3),
 ('CIS 118: Microsoft PowerShell/Command Line Operations', 'Day-to-day command line administration tasks of Microsoft Windows.',3),
 ('CIS 119: Mac Operating System', 'Specific topics include getting started with Mac OS.',3),
 ('CIS 120: Windows Operating System: Level II', 'Additional capabilities of the Windows program that configure devices and customize the presentation of the operating system.',3),
 ('CIS 122: Project Management Software: Level I', 'Utilization of project management software packages by managers and advanced business students to solve critical management planning tasks.',3),
 ('CIS 222: Project Management Software: Level II', 'Advanced use of project management software.',3),
 ('CIS 124: Linux Operating System', 'Introduction to the Linux Operating system.',3),
 ('CIS 126: Red Hat System Administration I', 'Introduction to core administration skills needed to manage a Red Hat Enterprise Linux system.',3),
 ('CIS 134: Internet/Web Development Level I', 'Overview of the Internet/World Wide Web (WWW) and its resources.',3),
 ('CIS 150: Content Management Systems: WordPress', 'Overview of WordPress Content Management System.',3),
 ('CIS 175: Object-Oriented Programming Fundamentals', 'Structured and Object-Oriented design and logic tools',3),
 ('CIS 127: Computer Game Development -Level I ', 'ntroduction to object-oriented game development, game design, and game theory.',3),
 ('CIS 156: Python Programming: Level I', 'Introduction to Python programming.',3),
 ('CIS 166: C#: Level I', 'Introduction to C# programming including general concepts, program design, development, data types, operators, expressions, flow control, functions, classes, input and output operations, debugging, structured programming, and object-oriented programming.',3),
 ('CIS 167: Java Programming: Level I ', 'Introduction to Java programming. Includes features needed to construct Java Applets, Java Applications, control structures, methods, arrays, character and string manipulation, graphics, and object-oriented programming.',3),
 ('CIS 182: Introduction to IOS Application Development', 'Introduction to iOS device programming utilizing the XCode application, and the programming languages Objective-C and/or Swift, utilizing various iOS frameworks.',3),
 ('CIS 185: Introduction to Android Application Development', 'Beginning with an overview of Android features, this class explores the required software tools and programming techniques for developing Android device applications.',3),
 ('CIS 197: Introduction to Javascript', 'ntroduction to basic JavaScript programming concepts including syntax. ',3),
 ('CIS 234: Internet/Web Development Level II', 'Plan, design and create web sites using HTML and Advanced Cascading Style Sheets (CSS).',3),
 ('CIS 149: Web Scripting with PHP: Hypertext Preprocessor (PHP)', 'Introduction to web scripting with PHP (PHP: Hypertext Preprocessor).',3),
 ('CIS 159: Linux System Administration', 'Managing Linux Operating Systems including  manipulation of file structures, backup systems, printing processes, troubleshooting, user account management, hard disk maintenance and configuration. ',3),
 ('CIS 334: Internet/Web Development Level III', 'Development of interactive websites with graphics, video, and sound using advanced web design techniques and tools.',3),
 ('CIS 256: Python Programming Level II ', 'Advanced Python object-oriented programming concepts and applications. ',3),
 ('CIS 266: C# Level II', 'Advanced C# programming with emphasis on data structures, dynamic memory allocation, object-oriented programming, user interfaces, and database processing.',3),
 ('CIS 267: Java Programming: Level II ', 'Intermediate Java programming. Includes features needed to construct object-oriented programming, multithreading, multimedia, files, streams and data structures. ',3),
 ('CIS 199: Advanced Information Technology Management', 'Course expands upon fundamental concepts and focuses on management of information technology systems in organizations. ',3),
 ('test', 'test',3);

 

       
 insert into section (course_id, instructor_id, dates, day, delivery, room, semester, time)
values (1, 1, 'January 8 - May 26', 'M-W-F', 'Hybrid', 'Saguaro 107', 'Spring', '10:30 AM'),
	   (2, 1, 'January 9 - May 27', 'M-W-F', 'Online','Saguaro - 108', 'Spring', '9:00 AM'),
	   (3, 2, 'January 10 - May 28', 'M-W-F','In-Person', 'Prickly Pear - 114', 'Spring', '11:45 AM'),
	   (4, 2, 'January 15 - June 1', 'M-W-F','In-Person', 'Cholla - 226', 'Spring', '1:15 PM'),
	   (5, 3, 'January 8 - May 26', 'M-W-F', 'In-Person','Golden Barrel - 345', 'Spring', '3:30 PM'),
	   (6, 3, 'January 9 - May 27', 'M-W-F', 'Hybrid','Organ Pipe - 101', 'Spring', '6:00 PM'),
	   (7, 4, 'January 10 - May 28', 'M-W', 'In-Person','Pincushion - 404', 'Spring', '7:30 PM'),
	   (8, 4, 'January 15 - June 1', 'M-W', 'Hybrid','Pincushion - 404', 'Spring', '10:30 AM'),
	   (9, 4, 'January 9 - May 27', 'M-W', 'Hybrid','Totem Pole - 167', 'Spring', '9:00 AM'),
	   (10, 5, 'January 10 - May 28', 'T-Th','In-Person', 'Prickly Pear - 114', 'Spring', '11:45 AM'),
	   (11, 5, 'January 8 - May 26', 'T-Th', 'Online','East Wing 107-A', 'Spring', '1:15 PM'),
	   (12, 6, 'January 9 - May 27', 'T-Th', 'In-Person','Totem Pole - 169', 'Spring', '3:30 PM'),
	   (13, 6, 'January 15 - June 1', 'T-Th','In-Person', 'Golden Barrel - 355', 'Spring', '6:00 PM'),
	   (14, 7, 'January 10 - May 28', 'T-Th','In-Person', 'East Wing 107-A', 'Spring', '7:30 PM'),
	   (15, 7, 'January 8 - May 26', 'T-Th', 'Online','Organ Pipe - 102', 'Spring', '7:30 PM'),
	   (16, 8, 'January 10 - May 28', 'T-Th', 'Online','Prickly Pear - 117', 'Spring', '10:30 AM'),
	   (17, 8, 'January 9 - May 27', 'M-W-F', 'In-Person','Cholla - 228', 'Spring', '9:00 AM'),
	   (18, 9, 'January 15 - June 1', 'M-W', 'Hybrid','Beavertail - 300', 'Spring', '7:30 PM'),
	   (19, 9, 'January 8 - May 26', 'T-Th', 'In-Person','Golden Barrel - 355', 'Spring', '3:30 PM'),
	   (20, 10, 'January 15 - June 1', 'T-Th', 'Hybrid','Cholla - 229', 'Spring', '1:15 PM'),
	   (22, 11, 'August 10 - December 5', 'M-W-F','In-Person', 'Saguaro - 108', 'Fall', '9:00 AM'),
	   (23, 11, 'August 11 - December 6','M-W-F', 'In-Person','Prickly Pear - 114', 'Fall', '11:45 AM'),
	   (24, 12, 'August 12 - December 7','M-W-F', 'In-Person','Cholla - 226', 'Fall', '1:15 PM'),
	   (25, 13, 'August 15 - December 10','M-W-F','Hybrid', 'Golden Barrel - 345', 'Fall', '3:30 PM'),
	   (26, 13, 'August 10 - December 5','M-W-F', 'In-Person','Organ Pipe - 101', 'Fall', '6:00 PM'),
	   (27, 14, 'August 11 - December 6','M-W', 'Hybrid','Pincushion - 404', 'Fall', '7:30 PM'),
	   (28, 15, 'August 12 - December 7','M-W', 'Online','Pincushion - 404', 'Fall', '10:30 AM'),
	   (29, 15, 'August 15 - December 10','M-W','In-Person', 'Totem Pole - 167', 'Fall', '9:00 AM'),
	   (30, 16, 'August 10 - December 5','T-Th', 'Hybrid','Prickly Pear - 114', 'Fall', '11:45 AM'),
	   (31, 17, 'August 11 - December 6','T-Th', 'Online','East Wing 107-A', 'Fall', '1:15 PM'),
	   (32, 18, 'August 12 - December 7','T-Th', 'In-Person','Totem Pole - 169', 'Fall', '3:30 PM'),
	   (33, 19, 'August 15 - December 10','T-Th', 'Online','Golden Barrel - 355', 'Fall', '6:00 PM'),
	   (34, 1, 'August 10 - December 5','T-Th', 'In-Person','East Wing 107-A', 'Fall', '7:30 PM'),
	   (35, 3, 'August 11 - December 6','T-Th', 'In-Person','Organ Pipe - 102', 'Fall', '7:30 PM'),
	   (36, 5, 'August 12 - December 7','T-Th', 'Hybrid','Prickly Pear - 117', 'Fall', '10:30 AM'),
	   (37, 7, 'August 15 - December 10','M-W-F','Online', 'Cholla - 228', 'Fall', '9:00 AM'),
	   (38, 9, 'August 10 - December 5','M-W', 'In-Person','Beavertail - 300', 'Fall', '7:30 PM'),
	   (39, 2, 'August 11 - December 6','T-Th','In-Person', 'Golden Barrel - 355', 'Fall', '3:30 PM'),
	   (39, 4, 'August 12 - December 7','T-Th', 'Online','Cholla - 229', 'Fall', '1:15 PM'),
	   (2, 6, 'June 10 - July 30', 'T-Th', 'In-Person','Cholla - 229', 'Summer', '1:15 PM'),
	   (4, 8, 'June 12 - July 29','M-W-F', 'Online','Saguaro - 108', 'Summer', '9:00 AM'),
	   (6, 10, 'June 12 - July 29','M-W-F', 'Online','Prickly Pear - 114', 'Summer', '11:45 AM'),
	   (8, 12, 'June 12 - July 29','M-W-F', 'Online','Cholla - 226', 'Summer', '1:15 PM'),
	   (10, 14, 'June 12 - July 29','M-W-F', 'Hybrid','Golden Barrel - 345', 'Summer', '3:30 PM'),
	   (12, 16, 'June 12 - July 29','M-W-F', 'In-Person','Organ Pipe - 101', 'Summer', '6:00 PM'),
	   (14, 18, 'June 15 - August 1','M-W', 'Hybrid','Pincushion - 404', 'Summer', '7:30 PM'),
	   (16, 19, 'June 15 - August 1','M-W', 'Online','Pincushion - 404', 'Summer', '10:30 AM'),
	   (18, 18, 'June 15 - August 1','M-W', 'Hybrid','Totem Pole - 167', 'Summer', '9:00 AM'),
	   (20, 17, 'June 10 - July 30','T-Th', 'In-Person','Prickly Pear - 114', 'Summer', '11:45 AM'),
	   (22, 16, 'June 10 - July 30','T-Th', 'In-Person','East Wing 107-A', 'Summer', '1:15 PM'),
	   (24, 15, 'June 10 - July 30','T-Th', 'Online','Totem Pole - 169', 'Summer', '3:30 PM'),
	   (26, 14, 'June 10 - July 30','T-Th', 'Hybrid','Golden Barrel - 355', 'Summer', '6:00 PM'),
	   (28, 12, 'June 10 - July 30','T-Th', 'In-Person','East Wing 107-A', 'Summer', '7:30 PM'),
	   (30, 11, 'June 10 - July 30', 'T-Th','Hybrid', 'Organ Pipe - 102', 'Summer', '7:30 PM'),
	   (32, 10, 'June 12 - July 29','T-Th', 'In-Person','Prickly Pear - 117', 'Summer', '10:30 AM'),
	   (34, 9, 'June 10 - July 30','M-W-F', 'Online','Cholla - 228', 'Summer', '9:00 AM'),
	   (36, 8, 'June 15 - August 1','M-W', 'Online','Beavertail - 300', 'Summer', '7:30 PM'),
	   (38, 7, 'June 10 - July 30','T-Th', 'Hybrid','Golden Barrel - 355', 'Summer', '3:30 PM'),
	   (1, 6, 'June 10 - July 30', 'T-Th', 'In-Person','Cholla - 229', 'Summer', '1:15 PM');
	   
	    
		
       
       

